server:
  standalone:
    enabled: true
    config: |
      storage "gcs" {
        bucket = "vault-koden"
        credentials_file = "/vault/userconfig/gcs.json"
      }
      listener "tcp" {
        address = "0.0.0.0:8200"
        tls_disable = 1
      }
      ui = true
  volumes:
    - name: gcs-creds
      secret:
        secretName: vault-gcs-credentials
  volumeMounts:
    - name: gcs-creds
      mountPath: /vault/userconfig
      readOnly: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  hosts:
    - host: vault.karned.bzh
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - vault.karned.bzh
      secretName: vault-tls
ui:
  enabled: true