apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-token-renew
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: renew-token
            image: your-dockerhub-username/vault-token-renew:latest
            env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_DB
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: VAULT_HOST
            - name: VAULT_PORT
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: VAULT_PORT
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: VAULT_TOKEN
          restartPolicy: OnFailure
