apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-token-renew
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: renew-token
            image: your-dockerhub-username/vault-token-renew:latest
            env:
            - name: VAULT_ADDR
              value: "https://vault.example.com"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token-secret
                  key: token
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password-secret
                  key: password
          restartPolicy: OnFailure
